### ISSUE TITLE
一个小的建议，针对bfe的监控增加路由配置

### ISSUE THREAD

**Issue by hexer-gogogo** [bfenetworks/bfe#1040]
**问题：**
目前bfe的监控只能通过ip:8421的形式进行访问，由于单位只给暴露一个端口，所以监控功能没有暴露出来。
所以想到用bfe代理监控127.1:8421的方式进行访问，但是由于代理需要设定一个服务code 
例如 `xxxx:8080/bfe-monitor -> 127.1:8421`
在进行访问的时候 页面的点击 会使`xxxx:8080/bfe-monitor/reload` 跳转成 `xxxx:8080/reload` 导致找不到product。

**建议如下：**
所以想到通过配置bfe monitor路由的方式进行访问 代码修改demo如下：
在`bfe`的`conf/bfe.conf`中增加`MonitorRouter`配置，来修改监控的访问跟路径， 例如
```
xxxx:8421/  访问监控首页 
--- MonitorRouter="/bfe-monitor-xxxx/" ---->  
xxxx:8421/bfe-monitor-xxxx/ 访问监控首页 
```
![WechatIMG16](https://user-images.githubusercontent.com/46989742/160974161-80bba5ab-7327-44cf-8869-c0c0d9254ef5.png)

**求助**
如果有更好的方式 通过只暴露8080也能访问监控， 那就更好了

**Comment by mileszhang2016** [comment]
1. "通过只暴露8080也能访问监控"，这个方式不可取，
(1) 会干扰正常的转发；
(2) 这样配置的话，外部也可以看到BFE的内部信息量，存在安全隐患
3. “在进行访问的时候 页面的点击 会使xxxx:8080/bfe-monitor/reload 跳转成 xxxx:8080/reload 导致找不到product”，这个问题没有看懂。能否再详细说一下？

**Comment by iyangsj** [comment]
@hexer-gogogo 这个需求场景非常特殊。基于当前版本的做法：

- **监控请求转发**：将"localhost:8421" 配置为一个特殊的后端集群；然后配置路由规则，将监控请求转发到该后端集群
  - 为了使monitor服务能正确处理请求，还需要配置rewrite规则修改请求（例如：去除/bfe_monitor 前缀)
  - 简化起见，也可以考虑直接使用特殊的域名来区分监控请求

- **入口访问控制**：为了避免监控信息暴露在外网，需额外配置访问限制规则（例如来源IP限制、请求携带认证头等）
  - 可以在mod_block模块中配置相应规则
