### ISSUE TITLE
Some unit tests failed

### ISSUE THREAD

**Issue by TrumanH** [bfenetworks/bfe#1056]
**Describe the bug**
Some unit tests failed:
* bfe_modules\mod_tcp_keepalive\mod_tcp_keepalive_test.go
```
--- FAIL: TestSetKeepAlive (1534.23s)
    mod_tcp_keepalive_test.go:70: CONN_TO_SET and CONN_SET_KEEP_IDLE and CONN_SET_KEEP_INTVL should be 1
```
* bfe_modules\mod_static\mod_static_test.go
```
--- FAIL: TestStaticFileHandlerNormalFile (0.17s)
    d:\opensource\bfe\bfe_modules\mod_static\mod_static_test.go:41: content-length should be 53, not 59
```
```
--- FAIL: TestStaticFileHandlerHeadMethod (0.15s)
    d:\opensource\bfe\bfe_modules\mod_static\mod_static_test.go:170: content-length should be 53, not 59
```

**To Reproduce**
run : `go test ./... -v`

**Expected behavior**
Fix failed UTs.

**Screenshots**
![image](https://user-images.githubusercontent.com/31583810/173336732-31315e97-598e-4dcb-aa22-1f22db9793d6.png)
![image](https://user-images.githubusercontent.com/31583810/173337710-85153287-5d21-4f94-b48b-47379811beb5.png)

**Additional context**
go version: go1.18.2
os: win11
branch: "develop" with no change.
![image](https://user-images.githubusercontent.com/31583810/173338843-e2344645-2b1a-422d-9b16-d595da15d457.png)

**Comment by daimg** [comment]
I can't re-product your issue. Do you run with latest code of develop branch?  

> --- FAIL: TestSetKeepAlive (1534.23s)
>     mod_tcp_keepalive_test.go:70: CONN_TO_SET and CONN_SET_KEEP_IDLE and CONN_SET_KEEP_INTVL should be 1
> 
Make sure you can connect to ip address 180.97.93.196, which is required by above case.


> bfe_modules\mod_static\mod_static_test.go
> --- FAIL: TestStaticFileHandlerNormalFile (0.17s)
>     d:\opensource\bfe\bfe_modules\mod_static\mod_static_test.go:41: content-length should be 53, not 59
> --- FAIL: TestStaticFileHandlerHeadMethod (0.15s)
>     d:\opensource\bfe\bfe_modules\mod_static\mod_static_test.go:170: content-length should be 53, not 59
> 

File bfe_modules/mod_static/testdata/mod_static/index.html should keep unchanged. Length of this file is 53. Please has a double check on it.

**Comment by TrumanH** [comment]
@daimg "Do you run with latest code of develop branch?" Yes, I just run test against the `develop` branch with no change.
I've updated issue description, added some screenshots and context infos.
