### ISSUE TITLE
是否支持 域名 转发呢 

### ISSUE THREAD

**Issue by hexergogo** [bfenetworks/bfe#1093]
配置的一般都是 ip:port 
![image](https://user-images.githubusercontent.com/46989742/212218834-a9556f9b-96c8-4991-8425-c6283231ccb8.png)

我尝试配置了 域名:port， 同时配置了/etc/hosts
![image](https://user-images.githubusercontent.com/46989742/212218873-b7a1e2cd-81cd-4357-869b-0e168384f7b7.png)
 
得到的却是404 或者其他，这个功能支持么，是我忽略了什么细节么

**Comment by ZhongShawn** [comment]
你好，你这个问题解决了么。我遇到了同样的困惑，BFE是否不支持 域名 转发方式

**Comment by hexergogo** [comment]
现在改成 ip+port 然后 header里面设置host了
