### ISSUE TITLE
Website does not have the correct trademark disclaimer

### ISSUE THREAD

**Issue by thisisobate** [bfenetworks/bfe#1147]
As part of our ongoing effort to https://github.com/cncf/techdocs/issues/198, we noticed that the website does not pass the trademark criteria on [CLOMonitor](https://clomonitor.io/search?foundation=cncf&not_passing_check=trademark_disclaimer&page=1).

To fix this:
Head to the source code of the website. In the `<footer>` section, add a **disclaimer** or **link** to the Linux foundation trademark disclaimer page:

**Disclaimer**
```
<footer>
   <p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>
</footer>
```

**Link**
```
 <footer>
      <ul>
          <li><a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademarks</a></li>
      </ul>
 </footer>
```

**Comment by codesmith25103** [comment]
Hey @thisisobate. I would like to work on this issue. Can you please assign me this?

**Comment by codesmith25103** [comment]
Hey @thisisobate and @iyangsj,

I’ve set up the project and made some necessary changes. However, I’m having trouble testing it before pushing my commit. I added the required link in the footer section, but I’m not sure how to build the website to check if the changes are reflected correctly. Could you please guide me? I’m new to open source, so I’m facing some issues.

**Comment by iyangsj** [comment]
@codesmith25103 The BFE website is created using [MkDocs](https://www.mkdocs.org/getting-started/), a straightforward static site generator.

Steps to set it up:

* Install MkDocs:

```
pip install mkdocs
```

* Build the site:
```
git clone https://github.com/bfenetworks/bfe
cd bfe/docs
make
```

* Preview the site:
```
cd output/en_us/
python3 -m http.server 8080
```

Open your browser and go to http://localhost:8080/

**Comment by codesmith25103** [comment]
"Hey @iyangsj, thanks for helping me out! I have one more question. I noticed that the following text is already added to the footer of the website:
<p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>

**Comment by iyangsj** [comment]
[The issue](https://github.com/cncf/techdocs/issues/198) has been closed as stale and outdated.
