### ISSUE TITLE
运行后直接退出

### ISSUE THREAD

**Issue by goodforever** [bfenetworks/bfe#532]
make 编译好了
如下运行后直接退出，什么动静也没有，访问相关端口当然也无法访问
$ cd output/bin/
$ ./bfe -c ../conf -l ../log

**Comment by iyangsj** [comment]
感谢关注及反馈！

可使用已发布版本：
https://www.bfe-networks.net/zh_cn/installation/install_using_binaries/

或基于最新的代码： 
（注：https://github.com/bfenetworks/bfe/pull/531 修复了缺失的配置目录 ）

**Comment by liuximu** [comment]
可以 tail -f  ./log/* 看看具体的报错，也可以开启调试模式看到更多的日志， -h 可以看到相关选项。
