### ISSUE TITLE
提示GetVip: cann`t get vip and port when Layer4LoadBalancer is not set

### ISSUE THREAD

**Issue by wednesdaygogo** [bfenetworks/bfe#537]
![image](https://user-images.githubusercontent.com/50281304/86330598-77ca4c80-bc7a-11ea-84f8-af3ed7e4ff46.png)

**Comment by xiaofei0800** [comment]
这个提示不影响基本转发功能（分流、rewrite等与VIP无关的功能）的使用。
截图中左侧curl访问无访问结果，可能是由于没有可用下游服务，返回500，curl可以增加-v查看访问过程。如果没有配置下游服务，可以将conf/cluster_conf/cluster_table.data 中的Addr和Port改为你的服务地址。
