### ISSUE TITLE
wrong handler type

### ISSUE THREAD

**Issue by FriendshipBridge** [bfenetworks/bfe#550]
https://github.com/bfenetworks/bfe/blob/81c549da3118da7a9add61e12876de6dfb28a691/bfe_module/bfe_callback.go#L78
https://github.com/bfenetworks/bfe/blob/81c549da3118da7a9add61e12876de6dfb28a691/bfe_module/bfe_callback.go#L79

Wrong handlerType when creating a HandlerList. It should be `HandlersAccept` instead of `HandleAccept`.

**Comment by iyangsj** [comment]
You are right! Thanks for your comments!
