### ISSUE TITLE
Adding deploy process in .travis.yml

### ISSUE THREAD

**Issue by odidev** [bfenetworks/bfe#565]
Hi Team, 

Os: Linux
Architecture: ARM64/AArch64
I have successfully built the package on my local arm64 system and Travis-CI as well and  packaged generated binaries as well into the ‘output’ folder. Currently, In releases we only have artifacts for AMD64 architecture. It will be very helpful to have a release with ARM64 artifacts. 
Travis logs: https://travis-ci.com/github/rahulgit-ps/bfe.

Can we add the deploy process in travis to release arm64 artifacts, or Please share your opinion on the same?

**Comment by iyangsj** [comment]
@odidev Yes, you can use travis to release arm64 artifacts. In addition, you can use [snapcraft](https://snapcraft.io/build/) to release arm64 artifact.

**Comment by iyangsj** [comment]
#570

**Comment by odidev** [comment]
@iyangsj : GitHub actions has not yet added arm64 support.. travis has arm64 support.

**Comment by iyangsj** [comment]
We can use GoReleaser to builds Go binaries for several platforms.
