### ISSUE TITLE
配置项如此之多，如何下手？

### ISSUE THREAD

**Issue by leceshide** [bfenetworks/bfe#568]
配置文件很多，data类都是json形式的，而且每个文件里定义的不一样（一块一块的小点）。是否能做成一个综合性的配置文件，比如：我在一个配置文件里就能配置我的集群、机房、机器、转发规则等？
如果我想更改更多的，我通过配置覆盖就可以里。
目前看，配置文件是对bfe非常熟悉的开发人员使用的，对于我们这些尚未入门的人很不友好

**Comment by iyangsj** [comment]
感谢你的关注和反馈！

基于配置文件方式管理的建议：
1.可基于 conf/ 目录中的基础配置进行修改
2.关于配置文件的组织详见：https://www.bfe-networks.net/zh_cn/configuration/config/
3.典型需求的配置方法详见：https://www.bfe-networks.net/zh_cn/example/guide/

未来会提供控制台及API方便管理配置。
