### ISSUE TITLE
Error occurs when return BfeHandlerFinish in ForwardFilter

### ISSUE THREAD

**Issue by wrayzheng** [bfenetworks/bfe#629]
**Describe the bug**
If return bfe_module.BfeHandlerFinish in a ForwardFilter (a module handler added to bfe_module.HandleForward callback point), bfe server will panic after executing this filter due to nil pointer dereference of variable 'res'. 

**To Reproduce**
Add a handler to bfe_module.HandleForward callback point, and make it return bfe_module.BfeHandlerFinish. When a request invokes this handler, program panics.

**Expected behavior**
Normally return a response to client.

**Additional context**
![image](https://user-images.githubusercontent.com/16437139/91790333-0fc8c000-ec43-11ea-84db-50b4f5940d86.png)

![image](https://user-images.githubusercontent.com/16437139/91789864-17d43000-ec42-11ea-9495-ed2cbc6e4e00.png)

**Comment by iyangsj** [comment]
@wrayzheng Thanks for your feedback!

**Comment by YuqiXiao** [comment]
That is a bug of bfe, we will fix this in this week;

**Comment by wrayzheng** [comment]
Alright. I wonder if a response variable will be added to the return values of forward filter in this fix?
For the moment, there is only one return value in forward filter which indicates the ACTION. It seems that I can not specify a custom response to be replied to client after executing a forward filter, when I want to stop the forwarding process and reply some error message.

**Comment by wrayzheng** [comment]
Or is there some alternative way to reply a custom response immediately after executing a forward filter? :)

**Comment by YuqiXiao** [comment]
@wrayzheng 
*I wonder if a response variable will be added to the return values of forward filter in this fix?*
Probably not, we may try to avoid close response's body when this response is nil pointer.

*Or is there some alternative way to reply a custom response immediately after executing a forward filter? :)*
We are strongly recommend you to do this in **AfterFoundLocation** filter instead of **forward**.  
BFE assume that **forward** is the state in which we can send request to backend but we need to add some extend info to request, like tell the backend how many times have BFE retried. 
So we *never* reply a custom response in our production environment and that's why we have not found this bug in almost 8 years.

**Comment by wrayzheng** [comment]
I got it. But my case is somewhat troublesome. I need to do something based on the backend after the backend balancing. And some error may occur in this phase, in which case an internal server error response is expected.
Though the forward filter it's not designed for such usage, but I don't find any other way to extend the logic, since the only extension mechanism is via BFE modules.

**Comment by wrayzheng** [comment]
Anyway, thanks for your reply~

**Comment by YuqiXiao** [comment]
@wrayzheng 
** in which case an internal server error response is expected. **
If you want some custom error response, here is some hints:
- Add information you need in req's context in `forward ` filter;
- BFE will get a 500 response by `CreateInternalSrvErrResp` and then go to `response_got`;
- In `response_got` BFE will use `HandleReadResponse` filter, and we normally deal response in this phase. So you may generate a custom error response in this phase with information in req's context;

**Comment by YuqiXiao** [comment]
like one module register in both `forward` and `HandleReadResponse` phase, add some info in `forward` and deal with this info in `HandleReadResponse`.

**Comment by wrayzheng** [comment]
Good idea. It works fine with the fixed logic.
