### ISSUE TITLE
关于VIP配置文件的疑问

### ISSUE THREAD

**Issue by akakZhang** [bfenetworks/bfe#675]
文档中对VIP的描述是“记录产品线的VIP列表”
实际使用中是否只是记录作用，是否会根据vip来选择product？如果确实会影响到product的选取，是否能描述一下使用场景。

**Comment by iyangsj** [comment]
@akakZhang 当前支持几种不同的使用场景：

1. 仅使用请求host来选择product （最常见场景）
这种情况下VIP配置文件为空

2. 仅使用VIP来选择product
这种情况下host配置文件为空

3. 组合使用域名及VIP来选择product
这种情况下host及vip配置文件同时有效；优先按host，然后按vip来选择product
