### ISSUE TITLE
向backend转发请求复用连接时间歇性出现unexpected EOF

### ISSUE THREAD

**Issue by iwannay** [bfenetworks/bfe#676]
在向后端转发请求时不定时的出现unexpected EOF，造成server_status 500状态码统计失真偏大。

原因初步分析是复用后端长连接时，服务器端请求已经关闭（未返回connection:close），在readLoop未正确关闭连接时，新请求复用此连接造成异常。

golang net/http（ https://github.com/golang/go/commit/5dd372bd1e70949a432d9b7b8b021d13abf584d1  )大约已对此问题进行修复。但是bfe_http中并未集成最新的代码。烦请bfe开发团队确认。

**Comment by iyangsj** [comment]
@iwannay 感谢你的反馈！你可以：

**方式一**：配置集群重试策略（[RetryLevel=1](https://www.bfe-networks.net/zh_cn/configuration/server_data_conf/cluster_conf.data/#_6)），将重试幂等请求（目前仅GET)

**方式二**：关闭与后端的长链接([MaxIdleConnsPerHost=0](https://www.bfe-networks.net/zh_cn/configuration/server_data_conf/cluster_conf.data/#_6))

适用于后端与bfe网络RTT较小(例如1ms内)，延迟可忽略场景； 
如果后端服务存在异常行为( 未规范返回connection:close，应修复后再启用长链接）

**Comment by iwannay** [comment]
@iyangsj 感谢作者，我先升级bfe_http部分代码到最新的http源码测试一下效果
