### ISSUE TITLE
Service Mesh support

### ISSUE THREAD

**Issue by qqeasonchen** [bfenetworks/bfe#682]
**Is your feature request related to a problem? Please describe.**
Is there any plan to let BFE act as a DATA PLANE(or sidecar ) and integrate with a control panel?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iyangsj** [comment]
@qqeasonchen It is a proposed feature(#277) and there are no concrete plans yet.
