### ISSUE TITLE
Support to output request/session log to stdout

### ISSUE THREAD

**Issue by wangrzneu** [bfenetworks/bfe#720]
**Is your feature request related to a problem? Please describe.**
I hope BFE can support to output request/session log to stdout, then logging mechanism in Docker or Kubernetes can be used. It is hard to deploy BFE and use mod_access in our Kubernetes cluster without it. 

**Describe the solution you'd like**
Add an option Log.LogFile in mod_access.conf, and set it to /dev/stdout. If the Log.LogFIle is set, other options like Log.LogPrefix, Log.LogDir, Log.RotateWhen and Log.BackupCount are ignored.

**Describe alternatives you've considered**
Store logs in a volume and use a sidecar to watch and output these logs to stdout.

**Comment by wangrzneu** [comment]
If you think it is a good feature. You can assign it to me.

**Comment by iyangsj** [comment]
@wangrzneu Thanks for your feedback! It's a good feature and the issue has been assigned to you.
