### ISSUE TITLE
多协程accept请求没有意义吧？

### ISSUE THREAD

**Issue by ccqy66** [bfenetworks/bfe#793]
```
	// start goroutine to accept http connections
	for i := 0; i < cfg.Server.AcceptNum; i++ {
		go func() {
			httpErr := bfeServer.ServeHttp(bfeServer.HttpListener)
			serveChan <- httpErr
		}()
	}
        // start goroutine to accept https connections
	for i := 0; i < cfg.Server.AcceptNum; i++ {
		go func() {
			httpsErr := bfeServer.ServeHttps(bfeServer.HttpsListener)
			serveChan <- httpsErr
		}()
	}
```
对于服务端同一个接口而言，多个协程调用并没有太多的意义吧。而且accept底层也会锁的存在，并不能提高服务的吞吐，反而会造成锁竞争

**Comment by iyangsj** [comment]
@ccqy66 一般情况下设置为1即可，这个机制适应如下条件的特殊场景：
- 流量特征是大量的短连接
- 单线程处理Accept出现瓶颈
- CPU核数较多且资源未被充分利用

**Comment by ccqy66** [comment]
@iyangsj 
我是不是可以这么理解：accept与handler_request有一些耗时区间，如果在区间内，有新的请求，可以通过新的协程来处理请求？例如下图：在t1的耗时区间，t2时刻，有新的请求，会起一个新的协程来处理。t3时刻类似。

t1  accept()---耗时-->handler_request
                      ↑
t2                   accpet()------耗时------>handler_request
                         ↑
t3                   accpet()----耗时--->handler_request

这这么理解，的确是有吞吐的提升。
