### ISSUE TITLE
支持接入到已有的注册中心做负载均衡吗？

### ISSUE THREAD

**Issue by brzyangg** [bfenetworks/bfe#796]
你好，近期在调研使用bfe系统，考虑到公司之前已经存在一个注册中心，想请问支持 开发模 块或者 其他方式 接入到已有的注册中心，来做一些自定义规则的负载均衡吗？

**Comment by iyangsj** [comment]
@brzyangg 感谢你的关注。支持两种方式：
- 方式1. 使用方可自行实现模块对接公司已有的服务注册中心，并更新实例列表配置
- 方式2. BFE的服务发现基于管理平台实现，管理平台预计下半年正式开源（后续可扩展支持新的注册中心）

**Comment by brzyangg** [comment]
@iyangsj 感谢回复，想请问下第一种方式：
`更新实例列表` 指的是更新相关集群实例的配置文件？

**Comment by iyangsj** [comment]
@brzyangg 参见https://www.bfe-networks.net/zh_cn/configuration/cluster_conf/cluster_table.data/

**Comment by brzyangg** [comment]
@iyangsj  明白了，感谢答复
