### ISSUE TITLE
configuration verify/test

### ISSUE THREAD

**Issue by clarinette9** [bfenetworks/bfe#800]
**Is your feature request related to a problem? Please describe.**
rovide a method to test/verify if the configuration is correct. before reload the config.
Like nginx -t

**Describe the solution you'd like**
Simple command.
After run,  print the test/verification result.

**Describe alternatives you've considered**

**Additional context**

**Comment by zhugelianglongming** [comment]
BFE配置验证工具

开源BFE程序包含了大量的配置文件，希望提供工具能对配置文件进行验证，主要要求如下：
-  检查完备性
     - 配置格式正确性：例如ini/json格式是否正确
     - 配置项值合法性：例如配置项取值是否合法
     - 配置依赖正确性：例如定义的产品线/集群等在相关联的多个配置文件中是否均存在
- 低维护成本
     - 在BFE新增配置文件时，应低成本扩展支持新配置的检查

配置工具的示例用法如下：
- 为bfe程序增加 -t 参数，执行配置检查功能
`./bfe -t -c <bfe-conf-root-dir>`

**Comment by kwanhur** [comment]
#846 track this issue, welcome to review it.
