### ISSUE TITLE
用户使用http协议访问强制跳转到https的问题

### ISSUE THREAD

**Issue by lf2186** [bfenetworks/bfe#802]
想用mod_redirect实现这个需求，
# vim conf/mod_redirect/redirect.data
{
    "Version": "init version",
    "Config": {
        "example_product": [
            {
                "Cond": "req_host_in(\"bfe01.example.com\")",
                "Actions": [
                    {
                        "Cmd": "SCHEME_SET",
                        "Params": ["HTTPS"]
                    }
                ],
                "Status": 301
            }
        ]
    }
}

1）条件原语有没有类似于req_scheme_in("http")的功能，取代上面的req_host_in？？解决上述配置会产生301死循环的问题；
2）bfe正确解决http跳转到https的做法是什么？麻烦提供下具体配置；

**Comment by iyangsj** [comment]
!req_proto_secure() && req_host_in("bfe01.example.com")
代表如果请求未基于HTTPS协议且域名为 bfe01.example.com

参考：
https://www.bfe-networks.net/zh_cn/condition/request/protocol/

**Comment by lf2186** [comment]
好的，感谢。
