### ISSUE TITLE
[Proposal] Add license tool to check files' license header declaration

### ISSUE THREAD

**Issue by kwanhur** [bfenetworks/bfe#868]
license tool like [license-eye](https://github.com/apache/skywalking-eyes) maybe help BFE to find out license relate problems:

1. files' license header content spelling mistake, lacking etc.
2. potential license incompatibility in dependent modules

for an example:

check files' license header
```bash
➜  bfe git:(develop) ✗ license-eye header check
INFO Loading configuration from file: .licenserc.yaml
INFO Totally checked 8592 files, valid: 507, invalid: 4, ignored: 8081, fixed: 0
ERROR the following files don't have a valid license header:
.gitignore
bfe_modules/mod_markdown/mod_markdown_test.go
docs/mkdocs_en.yml
docs/mkdocs_zh.yml
```

fix files' license header
```bash
➜  bfe git:(develop) ✗ license-eye header fix
INFO Loading configuration from file: .licenserc.yaml
INFO Totally checked 8592 files, valid: 507, invalid: 4, ignored: 8081, fixed: 4
```

check them again, all files' header had been validated
```bash
➜  bfe git:(develop) ✗ license-eye header check
INFO Loading configuration from file: .licenserc.yaml
INFO Totally checked 8592 files, valid: 511, invalid: 0, ignored: 8081, fixed: 0
```

it also can help to show what's the dependencies' license, see them [bfe-deps.license](https://gist.github.com/kwanhur/a53a09312645580ea94d4a946457c27c) on commit id `e81ac430`.

this file could help BFE to show license dependencies when release.

**Comment by iyangsj** [comment]
#879
