### ISSUE TITLE
找不到租户时，BFE返回用户定制的返回码

### ISSUE THREAD

**Issue by ohscartao** [bfenetworks/bfe#972]
当前一个请求到达BFE后，如果BFE找不到对应的租户，则返回HTTP status code 500。在有的场景下，用户可能希望返回自己定制的返回码，例如：可能要求返回404. 

针对找不到租户的场景，希望BFE能支持返回码的定制。

**Comment by mileszhang2016** [comment]
Refer to https://github.com/bfenetworks/bfe/discussions/958

**Comment by iyangsj** [comment]
@ohscartao  
[mod_errors ](https://www.bfe-networks.net/zh_cn/modules/mod_errors/mod_errors/)可以按需替换这类异常响应（例如将500响应替换为自定义响应）
